"""Описание изменений

Revision ID: e2ae46429450
Revises: 
Create Date: 2024-10-09 06:09:02.317136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2ae46429450'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('button', schema=None) as batch_op:
        batch_op.add_column(sa.Column('particulars', sa.String(length=152), nullable=True))
        batch_op.add_column(sa.Column('participant', sa.String(length=152), nullable=True))
        batch_op.drop_column('when')
        batch_op.drop_column('where')
        batch_op.drop_column('who')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('button', schema=None) as batch_op:
        batch_op.add_column(sa.Column('who', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('where', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('when', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('participant')
        batch_op.drop_column('particulars')

    # ### end Alembic commands ###
